import type { Deck } from "./deck-types";
export const hiraganaDeck: Deck = {
  id: "hiragana",
  name: "Hiragana",
  cards: [
    { front: "a", back: "あ" },
    { front: "i", back: "い" },
    { front: "u", back: "う" },
    { front: "e", back: "え" },
    { front: "o", back: "お" },
    { front: "ka", back: "か" },
    { front: "ki", back: "き" },
    { front: "ku", back: "く" },
    { front: "ke", back: "け" },
    { front: "ko", back: "こ" },
    { front: "sa", back: "さ" },
    { front: "shi", back: "し" },
    { front: "su", back: "す" },
    { front: "se", back: "せ" },
    { front: "so", back: "そ" },
    { front: "ta", back: "た" },
    { front: "chi", back: "ち" },
    { front: "tsu", back: "つ" },
    { front: "te", back: "て" },
    { front: "to", back: "と" },
    { front: "na", back: "な" },
    { front: "ni", back: "に" },
    { front: "nu", back: "ぬ" },
    { front: "ne", back: "ね" },
    { front: "no", back: "の" },
    { front: "ha", back: "は" },
    { front: "hi", back: "ひ" },
    { front: "fu", back: "ふ" },
    { front: "he", back: "へ" },
    { front: "ho", back: "ほ" },
    { front: "ma", back: "ま" },
    { front: "mi", back: "み" },
    { front: "mu", back: "む" },
    { front: "me", back: "め" },
    { front: "mo", back: "も" },
    { front: "ya", back: "や" },
    { front: "yu", back: "ゆ" },
    { front: "yo", back: "よ" },
    { front: "ra", back: "ら" },
    { front: "ri", back: "り" },
    { front: "ru", back: "る" },
    { front: "re", back: "れ" },
    { front: "ro", back: "ろ" },
    { front: "wa", back: "わ" },
    { front: "wo", back: "を" },
    { front: "n", back: "ん" },
  ],
};