import type { Deck } from "./deck-types";

export const jlptN5Deck: Deck = {
  id: "jlpt-n5",
  name: "JLPT N5 Vocabulary",
  cards: [
    { front: "私", back: "わたし (I, me)" },
    { front: "あなた", back: "you" },
    { front: "彼", back: "かれ (he, him)" },
    { front: "彼女", back: "かのじょ (she, her)" },
    { front: "これ", back: "this" },
    { front: "それ", back: "that" },
    { front: "あれ", back: "that (over there)" },
    { front: "ここ", back: "here" },
    { front: "そこ", back: "there" },
    { front: "あそこ", back: "over there" },
    { front: "誰", back: "だれ (who)" },
    { front: "何", back: "なに (what)" },
    { front: "どこ", back: "where" },
    { front: "いつ", back: "when" },
    { front: "どうして", back: "why" },
    { front: "どうやって", back: "how" },
    { front: "はい", back: "yes" },
    { front: "いいえ", back: "no" },
    { front: "ありがとう", back: "thank you" },
    { front: "すみません", back: "excuse me, sorry" },
    { front: "お願いします", back: "please (request)" },
    { front: "おはよう", back: "good morning" },
    { front: "こんにちは", back: "hello, good afternoon" },
    { front: "こんばんは", back: "good evening" },
    { front: "さようなら", back: "goodbye" },
    { front: "おやすみ", back: "good night" },
    { front: "いただきます", back: "expression before eating" },
    { front: "ごちそうさまでした", back: "expression after eating" },
    { front: "はい、どうぞ", back: "here you go (offering something)" },
    { front: "おめでとう", back: "congratulations" },
    { front: "がんばって", back: "do your best, good luck" },
  ],
};  