import type { Deck } from "./deck-types";

export const jlptN5Deck: Deck = {
  id: "jlpt-n5",
  name: "JLPT N5 Vocabulary",
  cards: [
    { front: "わたし (I, me)", back: "私" },
    { front: "you", back: "あなた" },
    { front: "かれ (he, him)", back: "彼" },
    { front: "かのじょ (she, her)", back: "彼女" },
    { front: "this", back: "これ" },
    { front: "that", back: "それ" },
    { front: "that (over there)", back: "あれ" },
    { front: "here", back: "ここ" },
    { front: "there", back: "そこ" },
    { front: "over there", back: "あそこ" },
    { front: "だれ (who)", back: "誰" },
    { front: "なに (what)", back: "何" },
    { front: "where", back: "どこ" },
    { front: "when", back: "いつ" },
    { front: "why", back: "どうして" },
    { front: "how", back: "どうやって" },
    { front: "yes", back: "はい" },
    { front: "no", back: "いいえ" },
    { front: "thank you", back: "ありがとう" },
    { front: "excuse me, sorry", back: "すみません" },
    { front: "please (request)", back: "お願いします" },
    { front: "good morning", back: "おはよう" },
    { front: "hello, good afternoon", back: "こんにちは" },
    { front: "good evening", back: "こんばんは" },
    { front: "goodbye", back: "さようなら" },
    { front: "good night", back: "おやすみ" },
    { front: "expression before eating", back: "いただきます" },
    { front: "expression after eating", back: "ごちそうさまでした" },
    { front: "here you go (offering something)", back: "はい、どうぞ" },
    { front: "congratulations", back: "おめでとう" },
    { front: "do your best, good luck", back: "がんばって" },
  ],
};  