import type { Deck } from "./deck-types";

export const katakanaDeck: Deck = {
  id: "katakana",
  name: "Katakana",
  cards: [
    { front: "a", back: "ア" },
    { front: "i", back: "イ" },
    { front: "u", back: "ウ" },
    { front: "e", back: "エ" },
    { front: "o", back: "オ" },
    { front: "ka", back: "カ" },
    { front: "ki", back: "キ" },
    { front: "ku", back: "ク" },
    { front: "ke", back: "ケ" },
    { front: "ko", back: "コ" },
    { front: "sa", back: "サ" },
    { front: "shi", back: "シ" },
    { front: "su", back: "ス" },
    { front: "se", back: "セ" },
    { front: "so", back: "ソ" },
    { front: "ta", back: "タ" },
    { front: "chi", back: "チ" },
    { front: "tsu", back: "ツ" },
    { front: "te", back: "テ" },
    { front: "to", back: "ト" },
    { front: "na", back: "ナ" },
    { front: "ni", back: "ニ" },
    { front: "nu", back: "ヌ" },
    { front: "ne", back: "ネ" },
    { front: "no", back: "ノ" },
    { front: "ha", back: "ハ" },
    { front: "hi", back: "ヒ" },
    { front: "fu", back: "フ" },
    { front: "he", back: "ヘ" },
    { front: "ho", back: "ホ" },
    { front: "ma", back: "マ" },
    { front: "mi", back: "ミ" },
    { front: "mu", back: "ム" },
    { front: "me", back: "メ" },
    { front: "mo", back: "モ" },
    { front: "ya", back: "ヤ" },
    { front: "yu", back: "ユ" },
    { front: "yo", back: "ヨ" },
    { front: "ra", back: "ラ" },
    { front: "ri", back: "リ" },
    { front: "ru", back: "ル" },
    { front: "re", back: "レ" },
    { front: "ro", back: "ロ" },
    { front: "wa", back: "ワ" },
    { front: "wo", back: "ヲ" },
    { front: "n", back: "ン" },
  ],
};  